#!/bin/bash
# Add GCE startup scripts and packages to the image.

DEBS="google-compute-daemon google-startup-scripts image-bundle gcutil"
for deb in $DEBS; do
  chroot $imagedir apt-get install --force-yes -y ${deb}
done

# These are startup scripts that are network services.
# This is normally disabled in Kali by default, so we need to manually enable.
chroot $imagedir update-rc.d ssh enable
chroot $imagedir update-rc.d google enable
chroot $imagedir update-rc.d google-address-manager enable
chroot $imagedir update-rc.d google-accounts-manager enable
