#!/bin/bash
# Basic sources.list

> $imagedir/etc/apt/sources.list

for apt_mirror in $apt_mirrors; do
cat >> $imagedir/etc/apt/sources.list <<EOF
deb $apt_mirror $codename main contrib non-free
deb-src $apt_mirror $codename main contrib non-free
EOF
done
