#!/bin/bash
# Register the snapshot as a new AMI

[ $arch = 'i386' ] && ami_arch='i386'
[ $arch = 'amd64' ] && ami_arch='x86_64'

ami_name="$distribution-$codename-$arch-$name_suffix"
log "Registering an AMI with the snapshot '$snapshot_id'"
ami_id=`euca-register \
	--name "$ami_name" --description "$description" \
	--architecture "$ami_arch" \
	--snapshot "$snapshot_id" --root-device-name "/dev/sda1" \
	--virtualization-type "hvm" \
	| awk '{print $2}'`

# If the user has already created an unnamed AMI today,
# this will fail, so give the AMI registration command to the user
if [[ ! "$ami_id" =~ ^ami-[0-9a-z]{8}$ ]]; then
	die \
		"Unable to register an AMI." \
		"You can do it manually with:" \
		"`which euca-register` \\\\" \
		"--name '$ami_name' --description '$description' \\\\" \
		"--architecture '$ami_arch' \\\\" \
		"--snapshot '$snapshot_id' --root-device-name '/dev/sda1' \\\\" \
		"--virtualization-type 'hvm'"
fi
log "Your AMI has been created with the ID '$ami_id'"
